language: ruby
rvm:
  - 1.9.3
before_script:
  - cd gsick
  - git clone https://github.com/rodjek/rspec-puppet.git
  - cd rspec-puppet
  - gem build rspec-puppet.gemspec
  - gem install rspec-puppet-*.gem
  - cd gsick/puppet-btsync
script: "rake test"
env:
  - PUPPET_VERSION=3.4.3
branches:
  only:
    - master
notifications:
  email: false
gemfile: Gemfile
