language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - ree
script: "rake test"
env:
  - PUPPET_VERSION=3.4.3
branches:
  only:
    - master
notifications:
  email: false
gemfile: Gemfile
before_script:
  - git clone https://github.com/rodjek/rspec-puppet.git
  - cd rspec-puppet
  - gem build rspec-puppet.gemspec
  - gem install rspec-puppet-*.gem