name         'gsick-btsync'
version      '0.0.3'
source       'https://github.com/gsick/puppet-btsync.git'
author       'Gamaliel Sick'
license      'MIT'
summary      'BTSync configuration module'
description  'Puppet module for installing Bittorrent Sync'
project_page 'https://github.com/gsick/puppet-btsync'

dependency   'puppetlabs/stdlib', '>= 4.1.0'
dependency   'pdxcat/singleton', '>= 0.0.5'